version: '3'
services:
  web-frontend:
    # build: ./web-frontend
    volumes:
      - ./web-frontend:/app
      - ./web-backend:/app/dist
      - /app/node_modules
    command : npm run build
    restart: "no"
  web-backend:
    environment:
      NODE_ENV: production
    ports:
      - '3005:3000'