version: '3'
services:
  web-backend:
    command : npm run devstart
    volumes:
      - ./web-backend:/app
      - /app/node_modules
  mysql:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 
      MYSQL_ROOT_PASSWORD: "mysqlrootpass"
  pma:
    links:
      - "mysql"
    environment:
        PMA_HOST: "mysql"
        PMA_USER: "apiuser"
        PMA_PASSWORD: "apipasswd"
    image: phpmyadmin/phpmyadmin:4.7
    ports:
        - "8080:80"